# Generated by Django 3.1.3 on 2020-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='image/escudo_times/'),
        ),
    ]
